apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: uk-print-project
  source:
    repoURL: https://github.com/YOUR_USERNAME/auth-service-gitops
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-uk-print
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true